set(OGRE_HOME "${CMAKE_CURRENT_LIST_DIR}/../../../system")
message(STATUS "OGRE_HOME = ${OGRE_HOME}")
if(UNIX)
	if(EXISTS "${OGRE_HOME}")
		set(CMAKE_MODULE_PATH "${OGRE_HOME}/lib/OGRE/cmake;${CMAKE_MODULE_PATH}")
		set(OGRE_SAMPLES_INCLUDEPATH "${OGRE_HOME}/lib/OGRE/samples/Common/include/")
	elseif(EXISTS "/usr/local/lib/OGRE/cmake")
		set(CMAKE_MODULE_PATH "/usr/local/lib/OGRE/cmake/;${CMAKE_MODULE_PATH}")
		set(OGRE_SAMPLES_INCLUDEPATH "/usr/local/share/OGRE/samples/Common/include/")
	elseif(EXISTS "/usr/lib/OGRE/cmake")
		set(CMAKE_MODULE_PATH "/usr/lib/OGRE/cmake/;${CMAKE_MODULE_PATH}")
		set(OGRE_SAMPLES_INCLUDEPATH "/usr/share/OGRE/samples/Common/include/")
	else ()
		message(SEND_ERROR "Failed to find OGRE CMake module path.")
	endif()
endif(UNIX)
